# vim:sw=2:ts=2
name: 'Container update'
description: 'Update a container on baseimage update or other update'
author: 'Vilgot Fredenberg'
inputs:
  baseimage:
    description: 'Baseimage of container, format should be "author/image:tag", "standard" images should be "library/image:tag"'
    required: true
  image:
    description: 'Image of container, format should be "author/image:tag"'
    required: true
  debug:
    description: 'Enable debug'
    default: 'false'
  pypi:
    description: 'Pypi project name'
#others to be implemented on demand
outputs:
  should-update:
    description: 'Returns "true" or "false" whether one should update the container'
    value: ${{ steps.checker.outputs.should-update }}
runs:
  using: 'composite'
  steps:
    - run: echo baseimage=${{ inputs.baseimage }} image=${{ inputs.image }} debug=${{ inputs.debug }} pypi_project=${{ inputs.pypi }} > ${{ github.workspace }}/data
      shell: bash
    - id: checker
      run: ${{ github.action_path }}/script.sh
      shell: bash
